sudo: false

os:
  - osx
  - linux

node_js:
  - "4"
  
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install -g yarn
  - yarn
  - npm run vscode:prepublish

script:
  - npm test --silent